### ISSUE TITLE
warning during go get on alpine:3.6

### ISSUE THREAD

**Issue by blacktop** [hillu/go-yara#16] opened 2017-11-11 17:46 UTC
Not an error, just a warning.

```bash
# github.com/hillu/go-yara
../../hillu/go-yara/rules-callback.c: In function 'rules_callback':
../../hillu/go-yara/rules-callback.c:44:61: warning: passing argument 4 of 'addString' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
         addString(user_data, string->identifier, m->offset, m->data, (int)m->data_length);
                                                             ^
In file included from ../../hillu/go-yara/rules-callback.c:10:0:
cgo-gcc-export-header-prolog:54:13: note: expected 'void *' but argument is of type 'const uint8_t * {aka const unsigned char *}'
```

https://github.com/malice-plugins/yara/blob/master/Dockerfile

thank you for all your great work!

**Comment by blacktop** [comment] 2017-11-11 17:47
Whoops, there is a runtime error:

```bash
Assertion failed: compiler->errors == 0 (compiler.c: yr_compiler_add_file: 495)
SIGABRT: abort
PC=0x7fcbe02a378f m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x560e585cb286, 0xc4200596f0, 0xc459dcb020)
	/usr/lib/go/src/runtime/cgocall.go:131 +0xe8 fp=0xc4200596c0 sp=0xc420059680
github.com/hillu/go-yara._Cfunc_yr_compiler_add_file(0x560e59dcb020, 0x7fcbdfbe25a0, 0x7fcbdfbe2aa0, 0x7fcbdfbe2c80, 0x0)
	github.com/hillu/go-yara/_obj/_cgo_gotypes.go:559 +0x4f fp=0xc4200596f0 sp=0xc4200596c0
github.com/hillu/go-yara.(*Compiler).AddFile.func5(0x560e59dcb020, 0x7fcbdfbe25a0, 0x7fcbdfbe2aa0, 0x7fcbdfbe2c80, 0x0)
	/go/src/github.com/hillu/go-yara/compiler.go:114 +0xb9 fp=0xc420059728 sp=0xc4200596f0
github.com/hillu/go-yara.(*Compiler).AddFile(0xc420016b80, 0xc42000e0b0, 0x560e585cebc2, 0x6, 0x0, 0x0)
	/go/src/github.com/hillu/go-yara/compiler.go:114 +0x214 fp=0xc4200597a0 sp=0xc420059728
main.scanFile(0xc4200148c0, 0x49, 0x560e585ce232, 0x6, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/maliceio/malice-yara/yara.go:76 +0x242 fp=0xc420059878 sp=0xc4200597a0
main.main.func2(0xc42008a6e0, 0x0, 0x0)
	/go/src/github.com/maliceio/malice-yara/yara.go:261 +0x190 fp=0xc420059a90 sp=0xc420059878
github.com/urfave/cli.HandleAction(0x560e588d8120, 0xc42001f3a0, 0xc42008a6e0, 0x0, 0x0)
	/go/src/github.com/urfave/cli/app.go:502 +0xd6 fp=0xc420059ab8 sp=0xc420059a90
github.com/urfave/cli.(*App).Run(0xc420110000, 0xc420010360, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/urfave/cli/app.go:268 +0x6cc fp=0xc420059cb0 sp=0xc420059ab8
main.main()
	/go/src/github.com/maliceio/malice-yara/yara.go:304 +0x87f fp=0xc420059f88 sp=0xc420059cb0
runtime.main()
	/usr/lib/go/src/runtime/proc.go:185 +0x212 fp=0xc420059fe0 sp=0xc420059f88
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420059fe8 sp=0xc420059fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x6
rcx    0x7fcbe02a378f
rdx    0x0
rdi    0x2
rsi    0x7fff804ef910
rbp    0x7fff804ef910
rsp    0x7fff804ef8f8
r8     0x2000
r9     0x3
r10    0x8
r11    0x246
r12    0xc420089e10
r13    0x1
r14    0x0
r15    0xda
rip    0x7fcbe02a378f
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by hillu** [comment] 2017-11-11 20:10
It looks like the runtime error has been caused by calling AddFile after an error has occured (and been ignored). See [this comment](https://github.com/VirusTotal/yara/blob/1d1dde67e76939fc3f4a5ac0115be41bc03cb81c/libyara/compiler.c#L492) lin the YARA sources.

**Comment by blacktop** [comment] 2017-11-11 20:56
You are correct, thank you.  Yara is now much more intense about not just skipping over rules that fail to be added 😉

**Comment by hillu** [comment] 2017-11-11 21:07
perhaps this should be fixed in yara. Handling errors in the calling code by shooting the process in the head does not seem ideal to me.

**Comment by blacktop** [comment] 2017-11-11 21:12
True especially when people write these big yara rule files that can include things they have taken from other yara rules.  

I had to prune my default rules dir down a lot to get it to pass, because of duplicate rules, but I don't know if I threw away other good rules as well?  

Yara should allow for skipping duplicate rules (if rule is different not just name) and/or make a util to `lint` and `dedup` a rules dir?

**Comment by hillu** [comment] 2017-11-12 00:17
Since both issues that you reported here have been solved or at least diagnosed to be not a go-yara problem, I am closing this issue.

**Closed by hillu** 2017-11-12 00:17 UTC
