### ISSUE TITLE
Segfault with YARA 4.1.0 RC2

### ISSUE THREAD

**Issue by satta** [hillu/go-yara#88] opened 2021-04-06 14:32 UTC
Is this compatible with YARA 4.1.0? When trying to build this with that version in Debian unstable, I get test failures due to segfaults on amd64:
```
github.com/hillu/go-yara
   dh_auto_test -O--buildsystem=golang
	cd obj-x86_64-linux-gnu && go test -vet=off -v -p 6 github.com/hillu/go-yara
=== RUN   TestBasic
    cbpool_test.go:25: Get: Got expected panic: Attempt to get nonexistent value from pool
    cbpool_test.go:43: Delete: Got expected panic: Attempt to delete nonexistent value from pool
    cbpool_test.go:57: full pool: Got expected panic: cbPool storage exhausted
--- PASS: TestBasic (0.00s)
=== RUN   TestCompiler
    compiler_test.go:21: expected error: syntax error
--- PASS: TestCompiler (0.00s)
=== RUN   TestPanic
    compiler_test.go:31: Everything ok, MustCompile panicked: syntax error
--- PASS: TestPanic (0.00s)
=== RUN   TestWarnings
    compiler_test.go:43: Recorded Errors=[]yara.CompilerMessage{yara.CompilerMessage{Filename:"", Line:1, Text:"syntax error"}}, Warnings=[]yara.CompilerMessage(nil)
--- PASS: TestWarnings (0.00s)
=== RUN   TestCompilerIncludeCallback
    compiler_test.go:52: Processing include "existing" (from ns="default", file="")
    compiler_test.go:52: Processing include "non-existing" (from ns="default", file="")
    compiler_test.go:73: Compiler returned error on attempt to include non-existing rule: callback failed to provide include resource: non-existing
--- PASS: TestCompilerIncludeCallback (0.00s)
=== RUN   TestIterator
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x5985c8, 0x2a)
	/usr/lib/go-1.15/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/lib/go-1.15/src/runtime/signal_unix.go:726 +0x4ac

goroutine 11 [syscall]:
runtime.cgocall(0x544e60, 0xc000058dd0, 0x1)
	/usr/lib/go-1.15/src/runtime/cgocall.go:133 +0x5b fp=0xc000058da0 sp=0xc000058d68 pc=0x407ffb
github.com/hillu/go-yara._Cfunc_yr_rules_scan_mem_blocks(0x79c630, 0xc0001003f0, 0x8, 0x5443b0, 0x76b838, 0xc000000000, 0xc000000000)
	_cgo_gotypes.go:1567 +0x4d fp=0xc000058dd0 sp=0xc000058da0 pc=0x5353ad
github.com/hillu/go-yara.(*Rules).ScanMemBlocks.func1(0xc000010098, 0xc0001003f0, 0x0, 0x5c2080, 0xc00000e200, 0x76b838, 0x0, 0x7f5a029ce108)
	/build/golang-github-hillu-go-yara-4.0.5/obj-x86_64-linux-gnu/src/github.com/hillu/go-yara/rules.go:182 +0x145 fp=0xc000058e30 sp=0xc000058dd0 pc=0x540625
github.com/hillu/go-yara.(*Rules).ScanMemBlocks(0xc000010098, 0x5c36c0, 0xc00000e220, 0x0, 0x0, 0x5c2080, 0xc00000e200, 0x0, 0x0)
	/build/golang-github-hillu-go-yara-4.0.5/obj-x86_64-linux-gnu/src/github.com/hillu/go-yara/rules.go:182 +0x285 fp=0xc000058ef0 sp=0xc000058e30 pc=0x53a545
github.com/hillu/go-yara.TestIterator(0xc000130480)
	/build/golang-github-hillu-go-yara-4.0.5/obj-x86_64-linux-gnu/src/github.com/hillu/go-yara/mem_blocks_test.go:54 +0xda fp=0xc000058f80 sp=0xc000058ef0 pc=0x52a4da
testing.tRunner(0xc000130480, 0x59c310)
	/usr/lib/go-1.15/src/testing/testing.go:1123 +0xef fp=0xc000058fd0 sp=0xc000058f80 pc=0x4e206f
runtime.goexit()
	/usr/lib/go-1.15/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000058fd8 sp=0xc000058fd0 pc=0x471541
created by testing.(*T).Run
	/usr/lib/go-1.15/src/testing/testing.go:1168 +0x2b3

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000130480, 0x58fcf9, 0xc, 0x59c310, 0x489901)
	/usr/lib/go-1.15/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc000001980)
	/usr/lib/go-1.15/src/testing/testing.go:1439 +0x78
testing.tRunner(0xc000001980, 0xc000057cf0)
	/usr/lib/go-1.15/src/testing/testing.go:1123 +0xef
testing.runTests(0xc00000e0a0, 0x685300, 0x27, 0x27, 0xc01331720406f728, 0x8bb31abbc6, 0x69a980, 0xc000057db8)
	/usr/lib/go-1.15/src/testing/testing.go:1437 +0x2fe
testing.(*M).Run(0xc000122000, 0x0)
	/usr/lib/go-1.15/src/testing/testing.go:1345 +0x1eb
github.com/hillu/go-yara.TestMain(0xc000122000)
	/build/golang-github-hillu-go-yara-4.0.5/obj-x86_64-linux-gnu/src/github.com/hillu/go-yara/main_test.go:35 +0x1a5
main.main()
	_testmain.go:125 +0x165
FAIL	github.com/hillu/go-yara	0.024s
FAIL

```

**Comment by hillu** [comment] 2021-04-06 15:52
Great catch. Apparently, YARA needs all the function pointers of `YR_MEMORY_BLOCK_ITERATOR` to be initialized with non-zero pointers (and the structure layout has changed for 4.1.0). The workaround below fixes the issue for me, but I think that this can (and should be) fixed in YARA itself.

``` diff
--- a/mem_blocks.go
+++ b/mem_blocks.go
@@ -16,6 +16,7 @@ uint8_t* memoryBlockFetchNull(YR_MEMORY_BLOCK*);
 
 YR_MEMORY_BLOCK* memoryBlockIteratorFirst(YR_MEMORY_BLOCK_ITERATOR*);
 YR_MEMORY_BLOCK* memoryBlockIteratorNext(YR_MEMORY_BLOCK_ITERATOR*);
+uint64_t memoryBlockIteratorSize(YR_MEMORY_BLOCK_ITERATOR*);
 */
 import "C"
 import (
@@ -60,9 +61,11 @@ func makeMemoryBlockIteratorContainer(mbi MemoryBlockIterator) (c *memoryBlockIt
 // pool.
 func makeCMemoryBlockIterator(c *memoryBlockIteratorContainer) (cmbi *C.YR_MEMORY_BLOCK_ITERATOR) {
        return &C.YR_MEMORY_BLOCK_ITERATOR{
-               context: callbackData.Put(c),
-               first:   C.YR_MEMORY_BLOCK_ITERATOR_FUNC(C.memoryBlockIteratorFirst),
-               next:    C.YR_MEMORY_BLOCK_ITERATOR_FUNC(C.memoryBlockIteratorNext),
+               context:    callbackData.Put(c),
+               first:      C.YR_MEMORY_BLOCK_ITERATOR_FUNC(C.memoryBlockIteratorFirst),
+               next:       C.YR_MEMORY_BLOCK_ITERATOR_FUNC(C.memoryBlockIteratorNext),
+               file_size:  C.YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC(C.memoryBlockIteratorSize),
+               last_error: 0,
        }
 }
 
@@ -148,3 +151,8 @@ func memoryBlockIteratorNext(cmbi *C.YR_MEMORY_BLOCK_ITERATOR) *C.YR_MEMORY_BLOC
        c.MemoryBlock = c.MemoryBlockIterator.Next()
        return memoryBlockIteratorCommon(cmbi, c)
 }
+
+//export memoryBlockIteratorSize
+func memoryBlockIteratorSize(cmbi *C.YR_MEMORY_BLOCK_ITERATOR) C.uint64_t {
+       return C.YR_UNDEFINED
+}
```

**Comment by ozanh** [comment] 2021-04-06 16:31
Hi, what a coincidence I've just implemented such a patch like yours @hillu to work with yara 4.1.0-rc2. I agree with you that yara should assign default function if file_size callback is missing as it assigns `_undefined_file_size` function in process scan. 

go-yara's unit tests seems to be working with this patch except one `TestScannerLastError`, I think matches more than YR_MAX_STRING_MATCHES does not return error any more may be warning, I don't know.

**Comment by ozanh** [comment] 2021-04-07 07:24
Hi @hillu thanks for opening an issue for this. However I don't know if this is going to be reflected to yara immediately.
I have to use yara 4.1 because previous versions does not support `arm64` architecture. Is it possible to create a branch for `4.1` including your patch above so we can add go-yara to our CI pipeline with go modules branch support until this issue is fixed? I am currently patching both go-yara for yara 4.1 compatibility and yara itself for your linux process scan improvement.

**Comment by hillu** [comment] 2021-04-07 09:39
You can build YARA 4.0 for linux/arm64 just fine.

**Comment by ozanh** [comment] 2021-04-07 09:49
@hillu I tried before and I tried again to be sure, `make check` fails like below for arm64. When I put an issue about this on yara, I was told to use master branch of yara. I don't know if the failing test is a trivial assertion error but it seems it will be a problem on production. Interestingly, `make check` fails for 4.1.0-rc2 but it is due to a trivial asserting error in debug print.

```
==================================
   yara 4.0.5: ./test-suite.log
==================================

# TOTAL: 14
# PASS:  13
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-rules
================

FAIL test-rules (exit status: 139)

```

**Comment by hillu** [comment] 2021-04-07 10:29
Does the "test-rules" program crash with a segmentation fault? You should report that to the YARA bugtracker…

For what it's worth, it builds just fine on the Debian autobuilders (https://buildd.debian.org/status/package.php?p=yara&suite=bullseye) and there the tests definitely get run.

**Comment by ozanh** [comment] 2021-04-07 10:55
I didn't get segmentation fault or a crash, only a failing test.
 I am convinced that it is built and tested under Debian well with all modules under arm64. I was testing on virtual Ubuntu 20.04 under Apple M1. There may be lots of reasons for failing test so I will stick to 4.0.5 version. Thank you for your help 👍

**Comment by hillu** [comment] 2021-04-07 12:03
Please paste the contents of `test-rules.log`. The message "exit status: 139" suggests that the test program segfaulted.

**Comment by ozanh** [comment] 2021-04-07 12:24
`test-rules.log` does not say more, it is `FAIL test-rules (exit status: 139)`
I pasted whole build and test terminal output below. Let me know if there is any additional flag to identify the problem.

```
ozan@ubuntu:~/Downloads/yara-4.0.5$ ./bootstrap.sh 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:20: installing 'build-aux/ar-lib'
configure.ac:20: installing 'build-aux/compile'
configure.ac:38: installing 'build-aux/config.guess'
configure.ac:38: installing 'build-aux/config.sub'
configure.ac:8: installing 'build-aux/install-sh'
configure.ac:8: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
configure.ac: installing 'build-aux/ylwrap'
ozan@ubuntu:~/Downloads/yara-4.0.5$ ./configure --enable-cuckoo --enable-magic --enable-debug --enable-dotnet --enable-macho --enable-dex
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... none needed
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for inline... inline
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking for isnan in -lm... yes
checking for log2 in -lm... yes
checking for strlcpy... no
checking for strlcat... no
checking for memmem... yes
checking for timegm... yes
checking for _mkgmtime... no
checking for clock_gettime... yes
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking jansson.h usability... yes
checking jansson.h presence... yes
checking for jansson.h... yes
checking for json_loadb in -ljansson... yes
checking magic.h usability... yes
checking magic.h presence... yes
checking for magic.h... yes
checking for magic_open in -lmagic... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking openssl/md5.h usability... yes
checking openssl/md5.h presence... yes
checking for openssl/md5.h... yes
checking openssl/sha.h usability... yes
checking openssl/sha.h presence... yes
checking for openssl/sha.h... yes
checking openssl/asn1.h usability... yes
checking openssl/asn1.h presence... yes
checking for openssl/asn1.h... yes
checking openssl/crypto.h usability... yes
checking openssl/crypto.h presence... yes
checking for openssl/crypto.h... yes
checking openssl/bio.h usability... yes
checking openssl/bio.h presence... yes
checking for openssl/bio.h... yes
checking openssl/pkcs7.h usability... yes
checking openssl/pkcs7.h presence... yes
checking for openssl/pkcs7.h... yes
checking openssl/x509.h usability... yes
checking openssl/x509.h presence... yes
checking for openssl/x509.h... yes
checking openssl/safestack.h usability... yes
checking openssl/safestack.h presence... yes
checking for openssl/safestack.h... yes
checking for MD5_Init in -lcrypto... yes
checking for MD5_Update in -lcrypto... yes
checking for MD5_Final in -lcrypto... yes
checking for SHA256_Init in -lcrypto... yes
checking for SHA256_Update in -lcrypto... yes
checking for SHA256_Final in -lcrypto... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libyara/Makefile
config.status: creating libyara/yara.pc
config.status: executing depfiles commands
config.status: executing libtool commands
ozan@ubuntu:~/Downloads/yara-4.0.5$ make
Making all in libyara
make[1]: Entering directory '/home/ozan/Downloads/yara-4.0.5/libyara'
make  all-am
make[2]: Entering directory '/home/ozan/Downloads/yara-4.0.5/libyara'
  CC       modules/tests/tests.lo
  CC       modules/elf/elf.lo
  CC       modules/math/math.lo
  CC       modules/time/time.lo
  CC       modules/pe/pe.lo
  CC       modules/pe/pe_utils.lo
  CC       modules/cuckoo/cuckoo.lo
  CC       modules/magic/magic.lo
  CC       modules/hash/hash.lo
  CC       modules/dotnet/dotnet.lo
  CC       modules/macho/macho.lo
  CC       modules/dex/dex.lo
  CC       grammar.lo
  CC       ahocorasick.lo
  CC       arena.lo
  CC       atoms.lo
  CC       base64.lo
  CC       bitmask.lo
  CC       compiler.lo
  CC       endian.lo
  CC       exec.lo
  CC       exefiles.lo
  CC       filemap.lo
  CC       hash.lo
  CC       hex_grammar.lo
  CC       hex_lexer.lo
  CC       lexer.lo
  CC       libyara.lo
  CC       mem.lo
  CC       modules.lo
  CC       notebook.lo
  CC       object.lo
  CC       parser.lo
  CC       proc.lo
  CC       re.lo
  CC       re_grammar.lo
  CC       re_lexer.lo
  CC       rules.lo
  CC       scan.lo
  CC       scanner.lo
  CC       sizedstr.lo
  CC       stack.lo
  CC       stopwatch.lo
  CC       strutils.lo
  CC       stream.lo
  CC       threading.lo
  CC       proc/linux.lo
  CCLD     libyara.la
copying selected object files to avoid basename conflicts...
make[2]: Leaving directory '/home/ozan/Downloads/yara-4.0.5/libyara'
make[1]: Leaving directory '/home/ozan/Downloads/yara-4.0.5/libyara'
make[1]: Entering directory '/home/ozan/Downloads/yara-4.0.5'
  CC       cli/args.o
  CC       cli/threading.o
  CC       cli/yara.o
  CCLD     yara
  CC       cli/yarac.o
  CCLD     yarac
make[1]: Leaving directory '/home/ozan/Downloads/yara-4.0.5'
ozan@ubuntu:~/Downloads/yara-4.0.5$ make check
Making check in libyara
make[1]: Entering directory '/home/ozan/Downloads/yara-4.0.5/libyara'
make  check-am
make[2]: Entering directory '/home/ozan/Downloads/yara-4.0.5/libyara'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/ozan/Downloads/yara-4.0.5/libyara'
make[1]: Leaving directory '/home/ozan/Downloads/yara-4.0.5/libyara'
make[1]: Entering directory '/home/ozan/Downloads/yara-4.0.5'
make  test-arena test-alignment test-atoms test-api test-rules test-pe test-elf test-version test-bitmask test-math test-stack test-re-split test-exception test-macho test-dex test-dotnet 
make[2]: Entering directory '/home/ozan/Downloads/yara-4.0.5'
  CC       tests/test-arena.o
  CCLD     test-arena
  CC       tests/test-alignment.o
  CCLD     test-alignment
  CC       tests/test-atoms.o
  CC       tests/util.o
  CC       libyara/atoms.o
  CCLD     test-atoms
  CC       tests/test-api.o
tests/test-api.c: In function ‘main’:
tests/test-api.c:804:5: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
  804 |     chdir(top_srcdir);
      |     ^~~~~~~~~~~~~~~~~
  CCLD     test-api
  CC       tests/test-rules.o
tests/test-rules.c: In function ‘main’:
tests/test-rules.c:2808:5: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
 2808 |     chdir(top_srcdir);
      |     ^~~~~~~~~~~~~~~~~
  CCLD     test-rules
  CC       tests/test-pe.o
tests/test-pe.c: In function ‘main’:
tests/test-pe.c:11:5: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
   11 |     chdir(top_srcdir);
      |     ^~~~~~~~~~~~~~~~~
  CCLD     test-pe
  CC       tests/test-elf.o
  CCLD     test-elf
  CC       tests/test-version.o
  CCLD     test-version
  CC       tests/test-bitmask.o
  CCLD     test-bitmask
  CC       tests/test-math.o
  CCLD     test-math
  CC       tests/test-stack.o
  CCLD     test-stack
  CC       tests/test-re-split.o
  CCLD     test-re-split
  CC       tests/test-exception.o
  CCLD     test-exception
  CC       tests/test-macho.o
tests/test-macho.c: In function ‘main’:
tests/test-macho.c:13:5: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
   13 |     chdir(top_srcdir);
      |     ^~~~~~~~~~~~~~~~~
  CCLD     test-macho
  CC       tests/test-dex.o
  CCLD     test-dex
  CC       tests/test-dotnet.o
tests/test-dotnet.c: In function ‘main’:
tests/test-dotnet.c:11:5: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
   11 |     chdir(top_srcdir);
      |     ^~~~~~~~~~~~~~~~~
  CCLD     test-dotnet
make[2]: Leaving directory '/home/ozan/Downloads/yara-4.0.5'
make  check-TESTS
make[2]: Entering directory '/home/ozan/Downloads/yara-4.0.5'
make[3]: Entering directory '/home/ozan/Downloads/yara-4.0.5'
PASS: test-arena
PASS: test-alignment
PASS: test-atoms
PASS: test-api
./build-aux/test-driver: line 107: 148562 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: test-rules
PASS: test-pe
PASS: test-elf
PASS: test-version
PASS: test-bitmask
PASS: test-math
PASS: test-stack
PASS: test-re-split
PASS: test-exception
PASS: test-macho
PASS: test-dex
PASS: test-dotnet
============================================================================
Testsuite summary for yara 4.0.5
============================================================================
# TOTAL: 16
# PASS:  15
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to vmalvarez@virustotal.com
============================================================================
make[3]: *** [Makefile:1240: test-suite.log] Error 1
make[3]: Leaving directory '/home/ozan/Downloads/yara-4.0.5'
make[2]: *** [Makefile:1348: check-TESTS] Error 2
make[2]: Leaving directory '/home/ozan/Downloads/yara-4.0.5'
make[1]: *** [Makefile:1692: check-am] Error 2
make[1]: Leaving directory '/home/ozan/Downloads/yara-4.0.5'
make: *** [Makefile:1125: check-recursive] Error 1
ozan@ubuntu:~/Downloads/yara-4.0.5$ cat test-r
test-re-split      test-re-split.trs  test-rules.log     test-rules.yarc    
test-re-split.log  test-rules         test-rules.trs     
ozan@ubuntu:~/Downloads/yara-4.0.5$ cat test-rules.log 
FAIL test-rules (exit status: 139)
ozan@ubuntu:~/Downloads/yara-4.0.5$ cat test-suite.log 
==================================
   yara 4.0.5: ./test-suite.log
==================================

# TOTAL: 16
# PASS:  15
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-rules
================

FAIL test-rules (exit status: 139)

ozan@ubuntu:~/Downloads/yara-4.0.5$ uname -a
Linux ubuntu 5.8.0-49-generic #55~20.04.1-Ubuntu SMP Fri Mar 26 01:00:41 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
ozan@ubuntu:~/Downloads/yara-4.0.5$ 
```

**Comment by hillu** [comment] 2021-04-08 13:41
I was curious and ran a job on an ARM64 instance (Ubuntu/groovy) and I can reproduce the test failure with v4.0.5. And yes, this is a segmentation fault.

**Comment by ozanh** [comment] 2021-04-08 17:13
It may be good to document this bug and solution in the documentation of go-yara.

**Comment by hillu** [comment] 2021-05-10 20:13
@satta, we seem to have gone off-track a bit with build failures on ARM and such, but I think that the original issue can be closed now. The version in master (as of a few minutes ago) requires YARA 4.1 and builds fine.

**Closed by hillu** 2021-05-10 20:13 UTC

**Comment by hillu** [comment] 2021-05-10 20:27
Yeah, I am going to have another hard look at YARA 4.1 if there were any other API changes and then tag go-yara 4.1.0.

**Comment by satta** [comment] 2021-05-10 20:29
Excellent 👍🏻

**Comment by satta** [comment] 2021-06-07 12:08
Hi, thanks tor tagging 4.1.0! However, this does not seem to fix the original issue I reported here, I still get the segfault when running the tests during a Debian package build with the current libyara 4.1.0~rc2-1 in unstable.
Did I miss anything?

**Comment by hillu** [comment] 2021-06-07 22:19
I missed to upload 4.1.0-1 to Debian/experimental for one thing; if you use go-yara 4.1.0 with that version, it will run the tests just fine. I don't think that fixing go-yara 4.1.x to work around an issue with the yara 4.1 prerelease version is really worth it.

**Comment by satta** [comment] 2021-06-07 22:20
I see, No worries then, I'll just wait for the new 4.1.0 final relase update to experimental. Thanks 👍🏻
