### ISSUE TITLE
Building static binary

### ISSUE THREAD

**Issue by cyrus-mc** [hillu/go-yara#136] opened 2023-11-21 19:38 UTC
According to the documentation there are two steps required to build statically:

* add build tag `yara_static`
* set LDflags to include `extdldflags -static`.

I have set the build tag at the top of the main package as such:

```
//go:build yara_static
// +build yara_static

package main

import (
   ...
)

func main() {
   ...
)
```

I then invoke `go build` with `-tags=yara_static` and `-ldflags '-s -w -extldflags "-static"'`. 

Building results in multiple errors relating to `yara.Scanner`, `yara.NewCompiler`, etc undefined.

**Comment by hillu** [comment] 2023-11-23 20:26
Please tell me the environment you are trying to build go-yara in. Also, provide a complete minimal reproducer program and the exact error messages you are getting.

**Comment by hillu** [comment] 2024-01-10 18:35
@cyrus-mc ping?

**Comment by hillu** [comment] 2024-03-13 00:10
@cyrus-mc Since you haven't provided any more information, I'm closing this issue.

**Closed by hillu** 2024-03-13 00:10 UTC
